[package]
name = "mqttrust_core"
version = "0.4.0"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "MQTT Client "
readme = "../README.md"
keywords = ["mqtt", "no-std"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/mqttrust"
edition = "2018"
documentation = "https://docs.rs/mqttrust_core"

[lib]
name = "mqttrust_core"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
embedded-hal = { version = "=1.0.0-alpha.4" }
embedded-nal = "0.6.0"
embedded-time = "0.11.0"
nb = "^1"
heapless = { version = "^0.7", features = ["serde", "x86-sync-pool"] }
mqttrust = { version = "^0.4.0", path = "../mqttrust" }
bbqueue = "0.5"

log = { version = "^0.4", default-features = false, optional = true }
defmt = { version = "^0.2", optional = true }

[dev-dependencies]
dns-lookup = "1.0.3"


[features]
default = []

defmt-impl = ["defmt", "mqttrust/defmt-impl", "heapless/defmt-impl"]

defmt-default = ["defmt-impl"]
defmt-trace = ["defmt-impl"]
defmt-debug = ["defmt-impl"]
defmt-info = ["defmt-impl"]
defmt-warn = ["defmt-impl"]
defmt-error = ["defmt-impl"]
